[package]
name = "test-suite"
version = "0.1.0"
edition = "2021"

[dependencies]
allure-rust = { path = "../allure-rust" }
allure-rust-core = { path = "../allure-rust-core" }

[dev-dependencies]
serde_json = "1.0"
uuid = { version = "1.3", features = ["v4"] }
tempfile = "3.8"
serial_test = "3.0"
